name: KeysX
api: 2.0.0
main: Junkdude\Key
version: 1.0
author: Junkdude
website: http://github.com/JunkDaCoder
commands:
  key:
    description: "Crates initial command."
  givekey:
    description: "Gives dat sweet cratekey dawg"  
